package application.api.ProductApi;

import application.services.RepositoryProductService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import application.models.*;

@RestController
@RequestMapping("product/all")
@CrossOrigin("*")
public class GetAllProducts {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data

    private RepositoryProductService getAll;

    @GetMapping
    public Iterable<Product> getAll() {
        return getAll.findAll();
    }
}
