package application.api.ProductApi;

import application.services.RepositoryProductService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import application.models.*;

@RestController
@RequestMapping("/demo")
public class MainController {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    @GetMapping("/add") // Map ONLY GET Requests
    public String addNewUser (@RequestParam String name, @RequestParam String email, @RequestParam String password,
                              @RequestParam int age, @RequestParam int id_company){
        User user = new User(0, name, email, password, age, id_company);
        userRepository.save(user);
        return "Saved";
    }

    @GetMapping(path="/all")
    public Iterable<User> getAllUsers() {
        // This returns a JSON or XML with the users
        return userRepository.findAll();
    }
}