-- MySQL Script generated by MySQL Workbench
-- Thu Mar  4 22:11:23 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema stallshop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema stallshop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `stallshop` DEFAULT CHARACTER SET utf8 ;
USE `stallshop` ;

-- -----------------------------------------------------
-- Table `stallshop`.`Company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stallshop`.`Company` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `web` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `phone` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stallshop`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stallshop`.`User` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `age` INT NOT NULL,
  `company_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `company_id_idx` (`company_id` ASC) VISIBLE,
  CONSTRAINT `company_id`
    FOREIGN KEY (`company_id`)
    REFERENCES `stallshop`.`Company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stallshop`.`Rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stallshop`.`Rol` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stallshop`.`User_Rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stallshop`.`User_Rol` (
  `id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `rol_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
  INDEX `rol_id_idx` (`rol_id` ASC) VISIBLE,
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `stallshop`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `rol_id`
    FOREIGN KEY (`rol_id`)
    REFERENCES `stallshop`.`Rol` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stallshop`.`sale`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stallshop`.`sale` (
  `id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `state_details` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `stallshop`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stallshop`.`Invoice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stallshop`.`Invoice` (
  `id` INT NOT NULL,
  `sale_id` INT NOT NULL,
  `Client_name` VARCHAR(45) NOT NULL,
  `Date` DATE NOT NULL,
  `Total_due` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `sale_id_idx` (`sale_id` ASC) VISIBLE,
  CONSTRAINT `sale_id`
    FOREIGN KEY (`sale_id`)
    REFERENCES `stallshop`.`sale` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stallshop`.`service`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stallshop`.`service` (
  `id` INT NOT NULL,
  `Information` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stallshop`.`Invoice_Detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stallshop`.`Invoice_Detail` (
  `id` INT NOT NULL,
  `invoice_id` INT NULL,
  `product_id` INT NULL,
  `Service_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `Service_id_idx` (`Service_id` ASC) VISIBLE,
  INDEX `invoice_id_idx` (`invoice_id` ASC) VISIBLE,
  CONSTRAINT `Service_id`
    FOREIGN KEY (`Service_id`)
    REFERENCES `stallshop`.`service` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `invoice_id`
    FOREIGN KEY (`invoice_id`)
    REFERENCES `stallshop`.`Invoice` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stallshop`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stallshop`.`Product` (
  `id` INT NOT NULL,
  `product_type_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `Price` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stallshop`.`Product_Propertie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stallshop`.`Product_Propertie` (
  `id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `value` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stallshop`.`Product_Type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stallshop`.`Product_Type` (
  `id` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
