package application.api;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import application.models.*;

@RestController
@RequestMapping("/product")
@CrossOrigin("*")
public class ProductController {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data

    private ProductRepository productRepository;
    @PostMapping("/add") // Map ONLY GET Requests
    public String addNewUser (@RequestBody Product product){

        productRepository.save(product);

        return "Saved";
    }

    @GetMapping("/all")
    public Iterable<Product> getAll() {
        // This returns a JSON or XML with the users
        return productRepository.findAll();
    }
}
